[project]
name = "self-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sumran Harchirkar", email = "sumranharchirkar58@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.13.5",
]

[project.scripts]
self-rag = "self_rag:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
